/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import newpackage.ListaSimple;
import newpackage.ListaVertex;
import newpackage.MatrixGraph;
import org.graphstream.graph.Graph;

/**
 *
 * @author andy
 */
public class DeleteEl extends javax.swing.JFrame {
    public Inicio mywin;
    /**
     * Creates new form DeleteEl
     * @param mywin
     */
    public DeleteEl(Inicio mywin) {
        this.mywin = mywin;
        this.setLocationRelativeTo(null);
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        String almacenes = mywin.listaVersx.returnAlmacenes();
        String[] almacen = almacenes.split(",");
        Selector.setModel(new javax.swing.DefaultComboBoxModel(almacen));
    }

    private DeleteEl() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Selector = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(286, 161));
        setPreferredSize(new java.awt.Dimension(286, 161));
        setResizable(false);
        setSize(new java.awt.Dimension(286, 161));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Elemento a Eliminar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        Selector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectorActionPerformed(evt);
            }
        });
        getContentPane().add(Selector, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, 40));

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
            int counter = 0;
                mywin.listaVersx.delByName(Selector.getSelectedItem().toString());
            for(;counter<12;counter++){
                mywin.listaSimpe.delByNameFE(Selector.getSelectedItem().toString());
                mywin.listaSimpe.delByNameSCE(Selector.getSelectedItem().toString());
            }
            String almacenes = mywin.listaVersx.returnAlmacenes();
            String[] almacen = almacenes.split(",");

            MatrixGraph matrix = new MatrixGraph(mywin.listaVersx,mywin.listaSimpe,mywin.listaSimpe.getSize());


            Graph grafico = matrix.MotrarGraph();
            matrix.CrearNodes(grafico);
            matrix.CrearEdges(grafico);
            
            for (String almacen1 : almacen) {
                if (!mywin.listaSimpe.ExistFE(almacen1)) {
                    throw new Exception();
                }
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Hay un vertice aislado,reiniciando todo el programa");
            Inicio newWin=new Inicio();
            newWin.setVisible(true);
            mywin.dispose();
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteEl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteEl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteEl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteEl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteEl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Selector;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
