/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package Frames;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import newpackage.Funciones;
import newpackage.ListaSimple;
import newpackage.MatrixGraph;


/**
 *
 * @author andy
 */
public class NewCargar extends javax.swing.JFrame {

    static Funciones fc;
    static ListaSimple lista;
    static MatrixGraph mymatrix;
    public Inicio mywin;
    public File fichero;
    /**
     * Creates new form NewCargar
     */
    public NewCargar(Inicio mywin) {
        initComponents();
        fc = new Funciones();
        lista = new ListaSimple();
        this.mywin = mywin;
        initComponents();
        this.setLocationRelativeTo(null);
    }

 
    private NewCargar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JButton();
        guardartxt = new javax.swing.JButton();
        cargartxt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setText("CERRAR");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 249, -1, -1));

        guardartxt.setText("GUARDAR");
        guardartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardartxtActionPerformed(evt);
            }
        });
        getContentPane().add(guardartxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 202, -1, -1));

        cargartxt.setText("CARGAR ARCHIVO");
        cargartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargartxtActionPerformed(evt);
            }
        });
        getContentPane().add(cargartxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 202, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 77, 324, 107));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PRUEBA PROYECTO 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 37, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        mywin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void guardartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardartxtActionPerformed
        try{
            mywin.setListaVersx(fc.Leer_matrix(fichero.getAbsolutePath()));
            mywin.setListaSimpe(fc.Leer_txt(fichero.getAbsolutePath(),mywin.listaVersx));
            MatrixGraph matrix=new MatrixGraph(mywin.listaVersx,mywin.listaSimpe,mywin.listaSimpe.getSize());
            mywin.setMatrixre(matrix);
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "ERROR!!! NO SE QUÉ HICISTE PERO MAL!");
        };
    }//GEN-LAST:event_guardartxtActionPerformed

    private void cargartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargartxtActionPerformed
        JFileChooser fx = new JFileChooser();

        int seleccion = fx.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {

            fichero = fx.getSelectedFile();
            
            JOptionPane.showMessageDialog(null, "Debe guardar para mantener los cambios","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
        }

        try{
           
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "ERROR!!! NO SE QUÉ HICISTE PERO MAL!");
        }
    }//GEN-LAST:event_cargartxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewCargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewCargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewCargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewCargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewCargar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargartxt;
    private javax.swing.JButton close;
    private javax.swing.JButton guardartxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
